name: Build Windows

on:
  workflow_dispatch:

env:
  # Necessary for most environments as build failure can occur due to OOM issues
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
    # Failure in one platform build won't impact the others
      fail-fast: false
      matrix:
        build:
          - name: 'Remotify'
            platform:  'windows/amd64'
            os: 'windows-latest'
          
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build wails
        uses: dAppServer/wails-build-action@v2.2
        id: build
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          package: false
          go-version: '1.22'
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}} ${{inputs.build-name}}
          path: |
            */bin/
            *\bin\*
